FROM node:18-alpine AS build
RUN apk add --no-cache python3 make g++

RUN mkdir -p /install/
ENV PATH /install/node_modules/.bin:$PATH
ENV NODE_PATH /install/node_modules/


COPY package.json /install/package.json
COPY package-lock.json /install/package-lock.json
RUN cd install; npm install

WORKDIR /app/
COPY . /app/

RUN cd /app
