version: '3.9'

services:

  frontend:
    container_name: svelte
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - API_BASE_URL=http://localhost:8000
    ports:
      - 3000:3000
      - 15000:15000
    volumes:
      - ./src/:/app/src/
      - ./static/:/app/static/
    command: npm run dev-with-args-flag