version: '3.9'

services:

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - DOMAIN=http://localhosts
    ports:
      - 3000:3000
      - 15000:15000
    volumes:
      - ./src/:/app/src/
    command: npm run dev-with-args-flag