FROM node:18-alpine AS build
RUN apk add --no-cache python3 make g++

RUN mkdir -p /install/
ENV PATH /install/node_modules/.bin:$PATH
ENV NODE_PATH /install/node_modules/


COPY package.json /install/package.json
COPY package-lock.json /install/package-lock.json
RUN cd install; npm install


EXPOSE 3000
EXPOSE 15000

WORKDIR /app/
COPY . /app/

RUN cd ./app; npm run prep-mui

# Run `yarn dev` and set the host to 0.0.0.0 so we can access the web app from outside
#CMD ["npm", "dev", "--host", "0.0.0.0"]